# Change these first
owner: im-perativa # Your GitHub organization or username, where this repository lives
repo: stis-uptime # The name of this repository

sites:
  - name: Web STIS
    url: https://stis.ac.id
  - name: SIPADU (Old)
    url: https://stis.ac.id/sipadu/mahasiswa/index.php/login/index
  - name: SIPADU NG
    url: https://ws.sipadu.stis.ac.id/login
  - name: SIPADU OAuth
    url: https://ws.stis.ac.id
  - name: Web Student
    url: https://student.stis.ac.id
  - name: Remotelab
    url: https://remotelab.stis.ac.id
  - name: SIMPUS
    url: https://perpustakaan.stis.ac.id
  - name: Git
    url: https://git.stis.ac.id
  - name: Link Shortener
    url: https://s.stis.ac.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /stis-uptime
  logoUrl: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/static/img/Logo.png
  name: STIS Uptime
  introTitle: "**STIS Uptime**"
  introMessage: Status page untuk layanan Politeknik Statistika STIS
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
