# Change these first
owner: im-perativa # Your GitHub organization or username, where this repository lives
repo: stis-uptime # The name of this repository

sites:
  - name: Web STIS
    url: https://stis.ac.id
  - name: SIPADU (Old)
    url: https://stis.ac.id/sipadu/mahasiswa/index.php/login/index
    icon: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/assets/sipadu.png
  - name: SIPADU NG
    url: https://ws.sipadu.stis.ac.id/login
    icon: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/assets/sipadung.svg
  - name: SIPADU OAuth
    url: https://ws.stis.ac.id
    icon: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/assets/sipadung.svg
  - name: Web Student/Skripsi
    url: https://student.stis.ac.id
  - name: Remotelab
    url: https://remotelab.stis.ac.id
  - name: SIMPUS
    url: https://simpus.stis.ac.id
    icon: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/assets/simpus.png
  - name: SIMPUS-API
    url: https://api-simpus.stis.ac.id
    icon: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/assets/simpus.png
  - name: Gitlab
    url: https://git.stis.ac.id
  - name: Link Shortener
    url: https://s.stis.ac.id
  - name: Jurnal ASKS
    url: https://jurnal.stis.ac.id
  - name: Repo STIS
    url: https://repo.stis.ac.id
  - name: Profil Dosen STIS
    url: https://stis.ac.id/dosen
  - name: Prosiding (SEMNAS)
    url: https://prosiding.stis.ac.id
  - name: Prosiding Internasional (ICDSOS)
    url: https://proceedings.stis.ac.id/icdsos
  - name: SISTER Politeknik Statistika STIS
    url: https://sister.stis.ac.id
  - name: Web Alumni STIS
    url: https://alumni.stis.ac.id
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stis.ac.id
  logoUrl: https://raw.githubusercontent.com/im-perativa/stis-uptime/master/static/img/Logo.png
  name: STIS Uptime
  introTitle: "**STIS Uptime**"
  introMessage: Status page untuk layanan Politeknik Statistika STIS
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
